### ISSUE TITLE
Page Reload Issue

### ISSUE THREAD

**Issue by AnuraktSachan-CEDCOSS** [wpswings/upsell-order-bump-offer-for-woocommerce#102]
**Bug Name -** Page Reload Issue
**Area Path -** 
**Status -** New
**Woo Commerce Version -** 6.5.1
**WordPress Version -** 6.0.0
**Plugin Version -** 2.1.3
**Description -**

On demo / live site, when you want to buy any product and it comes under order bump, proceed it, and then you reach on check out page then page started reloading.

On the local site, your order was proceed properly. but after that page started reloading.

https://www.awesomescreenshot.com/video/9918626?key=6adc457fef0704378cf2f6d7a3427e21

https://www.awesomescreenshot.com/video/9918661?key=8705f65a880241ad1e14b30e30795144

**Comment by prince-cedcoss** [comment]
fix

**Comment by AnuraktSachan-CEDCOSS** [comment]
ok
