### ISSUE TITLE
You can provide a separate offer price with formate.

### ISSUE THREAD

**Issue by AnuraktSachan-CEDCOSS** [wpswings/upsell-order-bump-offer-for-woocommerce#105]
**Bug Name -** You can provide a separate offer price with formate.
**Area Path -** 
**Status -** New
**Woo Commerce Version -** 6.9.4
**WordPress Version -** 6.0.2
**Plugin Version -** 2.1.6
**Description -**

![image](https://user-images.githubusercontent.com/76723393/193531068-25d847ec-3bdf-4906-adf3-17eee70837f1.png)

**Comment by Sukirti-CEDCOSS** [comment]
verified
