### ISSUE TITLE
Difference between checkout total and cart popup total.

### ISSUE THREAD

**Issue by AnuraktSachan-CEDCOSS** [wpswings/upsell-order-bump-offer-for-woocommerce#106]
**Bug Name -** Difference between checkout total and cart popup total.
**Area Path -** 
**Status -** New
**Woo Commerce Version -** 6.9.4
**WordPress Version -** 6.0.2
**Plugin Version -** 2.1.6
**Description -**

Changes in the bump offer can not reflect in the cart popup.

![image](https://user-images.githubusercontent.com/76723393/193552447-f91a863a-1af4-4c23-a687-2dad00645a91.png)

![image](https://user-images.githubusercontent.com/76723393/193552504-fb54a960-af5a-40cf-b4e3-392cef31df6b.png)

**Comment by prince-cedcoss** [comment]
fixed

**Comment by AnuraktSachan-CEDCOSS** [comment]
ok
