### ISSUE TITLE
Notice with PHP 8.0.0

### ISSUE THREAD

**Issue by AnuraktSachan-CEDCOSS** [wpswings/upsell-order-bump-offer-for-woocommerce#107]
**Bug Name -** Notice with PHP 8.0.0
**Area Path -** 
**Status -** New
**Woo Commerce Version -** 6.9.4
**WordPress Version -** 6.0.2
**Plugin Version -** 2.1.6
**Description -**

![image](https://user-images.githubusercontent.com/76723393/194295067-683413aa-9c6e-4cf2-b414-0b59637c2f39.png)

**Comment by prince-cedcoss** [comment]
fixed

**Comment by AnuraktSachan-CEDCOSS** [comment]
ok
