### ISSUE TITLE
QA Issue

### ISSUE THREAD

**Issue by AnuraktSachan-CEDCOSS** [wpswings/upsell-order-bump-offer-for-woocommerce#112]
**Bug Name -** QA Issue
**Area Path -** 
**Status -** New
**Woo Commerce Version -** 7.2.2
**WordPress Version -** 6.1.1
**Plugin Version -** 2.1.8
**Description -**

Update * WC tested up to:         7.2.0 to 7.2.2

Commented Code 
public/css/upsell-order-bump-offer-for-woocommerce-public.css  
Line No. ->>  642-647

**Comment by prince-cedcoss** [comment]
fixed

**Comment by AnuraktSachan-CEDCOSS** [comment]
ok
