### ISSUE TITLE
Language Issue

### ISSUE THREAD

**Issue by AnuraktSachan-CEDCOSS** [wpswings/upsell-order-bump-offer-for-woocommerce#113]
**Bug Name -** Language Issue
**Area Path -** 
**Status -** New
**Woo Commerce Version -** 7.2.2
**WordPress Version -** 6.1.1
**Plugin Version -** 2.1.8
**Description -**

![image](https://user-images.githubusercontent.com/76723393/209118041-0f88cbff-be12-45b7-9d52-3eedce3e0edf.png)

**Comment by prince-cedcoss** [comment]
fixed

**Comment by AnuraktSachan-CEDCOSS** [comment]
ok
