### ISSUE TITLE
Theme compatibility Issue 

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/upsell-order-bump-offer-for-woocommerce#114]
Woo Commerce Version - 7.5.1
WordPress Version - 6.1.1
Plugin Version - 2.2.1
Description:
Theme: Avada
![image](https://user-images.githubusercontent.com/85384857/227893862-0e407d24-393f-462c-bf59-ff0e225e1ddc.png)
![image](https://user-images.githubusercontent.com/85384857/227893899-ba4f53ab-3f34-4561-ad69-9fe057fa6a97.png)

Theme: Divi
![image](https://user-images.githubusercontent.com/85384857/227896002-989ccb4d-b56e-47c6-b105-5831c052d76e.png)
![image](https://user-images.githubusercontent.com/85384857/227896084-369613c1-aaaf-4fe5-b637-adc0ae4797af.png)

**Comment by prince-cedcoss** [comment]
fixed the theme issue from Avada

**Comment by Sukirti-CEDCOSS** [comment]
verified
