### ISSUE TITLE
Darken the selected button for user convenience 

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/upsell-order-bump-offer-for-woocommerce#116]
Woo Commerce Version - 7.6.0
WordPress Version - 6.2.0
Plugin Version - 2.2.2
Description:
Darken the selected button for user convenience 
![image](https://user-images.githubusercontent.com/85384857/234174720-1df53ddf-7f2a-4a2b-a19f-4e6b99b7735f.png)

**Comment by prince-cedcoss** [comment]
fixed

**Comment by Sukirti-CEDCOSS** [comment]
verified
