### ISSUE TITLE
Add video UTM link

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/upsell-order-bump-offer-for-woocommerce#117]
Woo Commerce Version - 7.6.0
WordPress Version - 6.2.0
Plugin Version - 2.2.2
Description:
Add video UTM link
![image](https://user-images.githubusercontent.com/85384857/234246424-b0c8b765-142b-4175-83bd-68b03bcf7fc1.png)

**Comment by prince-cedcoss** [comment]
fixed

**Comment by Sukirti-CEDCOSS** [comment]
verified
