### ISSUE TITLE
The bumps are not working on the org plugin whereas the same is working on the pro plugin

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/upsell-order-bump-offer-for-woocommerce#118]
Woo Commerce Version - 7.6.0
WordPress Version - 6.2.0
Plugin Version - 2.2.2
Description:
The bumps are not working on the org plugin whereas the same is working on the pro plugin
[org_bump.zip](https://github.com/wpswings/upsell-order-bump-offer-for-woocommerce/files/11321516/org_bump.zip)

**Comment by prince-cedcoss** [comment]
fixed

**Comment by Sukirti-CEDCOSS** [comment]
verified
