### ISSUE TITLE
Warning appearing after installing CheckoutWC

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/upsell-order-bump-offer-for-woocommerce#119]
Woo Commerce Version - 7.7.1
WordPress Version - 6.2.2
Plugin Version - 2.2.3
Description:
Warning appearing after installing CheckoutWC
![image](https://github.com/wpswings/upsell-order-bump-offer-for-woocommerce/assets/85384857/c8a3631c-e293-4e48-9df7-d9465903cd0c)

**Comment by prince-cedcoss** [comment]
issue is fixed
