### ISSUE TITLE
PHPcs Issues

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/upsell-order-bump-offer-for-woocommerce#122]
Status - New
Woo Commerce Version - 7.8.0
WordPress Version - 6.2.2
Plugin Version - 2.2.0
Description:
[upsell-order-bump-offer-for-woocommerce.zip](https://github.com/wpswings/upsell-order-bump-offer-for-woocommerce/files/11934707/upsell-order-bump-offer-for-woocommerce.zip)
[PHPcs.xml.zip](https://github.com/wpswings/upsell-order-bump-offer-for-woocommerce/files/11934713/PHPcs.xml.zip)

**Comment by prince-cedcoss** [comment]
fixed the phpcs issue, some are not fixable  as they may affect the plugin functionality

**Comment by Sukirti-CEDCOSS** [comment]
verified
