### ISSUE TITLE
The image is not displayed on the preview as well as in the offer

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/upsell-order-bump-offer-for-woocommerce#126]
Woo Commerce Version - 8.0.0
WordPress Version - 6.3
Plugin Version - 2.2.5
Description:
The image is not displayed on the preview as well as in the offer
![image](https://github.com/wpswings/upsell-order-bump-offer-for-woocommerce/assets/85384857/be2da681-5207-4548-be53-63b43d11fde4)
![image](https://github.com/wpswings/upsell-order-bump-offer-for-woocommerce/assets/85384857/e261af93-edda-4f41-bca9-f66881103df6)

**Comment by prince-cedcoss** [comment]
fixed issue

**Comment by Sukirti-CEDCOSS** [comment]
Verified
