### ISSUE TITLE
Design issue

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/upsell-order-bump-offer-for-woocommerce#127]
Woo Commerce Version - 8.0.0
WordPress Version - 6.3
Plugin Version - 2.2.5
Description:
Image alignment is not proper
![image](https://github.com/wpswings/upsell-order-bump-offer-for-woocommerce/assets/85384857/5f8cd81e-3367-41ff-bde5-4c5bbf1c892c)

**Comment by prince-cedcoss** [comment]
the issue is not appearing on my storefront side.

**Comment by Sukirti-CEDCOSS** [comment]
fine for now
