### ISSUE TITLE
Add dotted outline and pro tag on new templates

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/upsell-order-bump-offer-for-woocommerce#128]
Woo Commerce Version - 8.0.0
WordPress Version - 6.3
Plugin Version - 2.2.5
Description:
Add dotted outline and pro tag on new templates
![image](https://github.com/wpswings/upsell-order-bump-offer-for-woocommerce/assets/85384857/63bb6677-a4e2-403d-a34c-348c54d4532e)

**Comment by prince-cedcoss** [comment]
pro tag added to the other template and for the dotted line, we don't have to show them in the image because they don't provide in that template.

**Comment by Sukirti-CEDCOSS** [comment]
fine for now
