### ISSUE TITLE
Out a validation that with any chosen product in recommend the pop up should on show 

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/upsell-order-bump-offer-for-woocommerce#129]
Status - New
Woo Commerce Version - 8.0.0
WordPress Version - 6.3
Plugin Version - 2.2.0
Description:
Out a validation that with any chosen product in recommend the pop up should on show 
![image](https://github.com/wpswings/upsell-order-bump-offer-for-woocommerce/assets/85384857/e432df1b-8eae-4a31-827e-3413e5b25d6c)
![image](https://github.com/wpswings/upsell-order-bump-offer-for-woocommerce/assets/85384857/11cb0ac2-4d58-4981-ad33-da4884899b6f)

**Comment by prince-cedcoss** [comment]
fixed this issue in the update now

**Comment by Sukirti-CEDCOSS** [comment]
verified
