### ISSUE TITLE
PHPcs 

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/upsell-order-bump-offer-for-woocommerce#131]
[PHPcs.xml.zip](https://github.com/wpswings/upsell-order-bump-offer-for-woocommerce/files/12674612/PHPcs.xml.zip)
[upsell-order-bump-offer-for-woocommerce.zip](https://github.com/wpswings/upsell-order-bump-offer-for-woocommerce/files/12674614/upsell-order-bump-offer-for-woocommerce.zip)

**Comment by prince-cedcoss** [comment]
fixed

**Comment by Sukirti-CEDCOSS** [comment]
verified
