### ISSUE TITLE
The banner image is not displayed on the plugin page and also the dashboard.

### ISSUE THREAD

**Issue by pranjali-wps** [wpswings/upsell-order-bump-offer-for-woocommerce#132]
WP Version - 6.3.2
WC Version - 8.2.1
Plugin Version - 2.2.8
Description - The banner image is not displayed on the plugin page and also the dashboard.

![image](https://github.com/wpswings/upsell-order-bump-offer-for-woocommerce/assets/129398279/19a7ae80-f7d1-45a2-9528-f8251d32862d)

**Comment by prince-cedcoss** [comment]
fixed

**Comment by pranjali-wps** [comment]
issue fixed
