### ISSUE TITLE
 When I have entered any product for the target product then list product is not displayed properly.

### ISSUE THREAD

**Issue by pranjali-wps** [wpswings/upsell-order-bump-offer-for-woocommerce#133]
WP Version - 6.3.2
WC Version - 8.2.1
Plugin Version -  2.2.8
Disclaimer - When I have entered any product for the target product the list product is not displayed properly.

[scrnli_29_10_2023_13-42-06.webm](https://github.com/wpswings/upsell-order-bump-offer-for-woocommerce/assets/129398279/0c521716-6ef4-40f3-9f4b-4fdc16830a08)

**Comment by prince-cedcoss** [comment]
the issue is fixed on side and it works properly. Please check again.
so, for now it is fixed

**Comment by pranjali-wps** [comment]
issue fixed
