### ISSUE TITLE
All dropdowns are not visible properly.  

### ISSUE THREAD

**Issue by pranjali-wps** [wpswings/upsell-order-bump-offer-for-woocommerce#134]
WP Version - 6.3.2
WC Version - 8.2.1
Plugin Version - 2.2.8
Disclaimer - All dropdowns are not visible properly.

[scrnli_29_10_2023_13-48-37.webm](https://github.com/wpswings/upsell-order-bump-offer-for-woocommerce/assets/129398279/ea9ff37d-fdba-46c9-afa9-1fe19b039527)

**Comment by prince-cedcoss** [comment]
the issue is fixed on side and it works properly. Please check  again.
so, for now it is fixed

**Comment by pranjali-wps** [comment]
issue fixed
