### ISSUE TITLE
 There should be a description for Live and Sandbox. 

### ISSUE THREAD

**Issue by pranjali-wps** [wpswings/upsell-order-bump-offer-for-woocommerce#135]
WP Version - 6.3.2
WC Version - 8.2.1
Plugin Version - 2.2.8
Disclaimer - There should be a description for Live and Sandbox. 

Note: Same as it is applied on the Upsell funnel for the woo-commerce Plugin.

![Screenshot at 2023-10-30 13-44-29](https://github.com/wpswings/upsell-order-bump-offer-for-woocommerce/assets/129398279/396c8aa6-7691-4909-a03e-c8668f522920)

**Comment by prince-cedcoss** [comment]
fixed

**Comment by pranjali-wps** [comment]
issue fixed
