### ISSUE TITLE
Please Remove Skype link  

### ISSUE THREAD

**Issue by pranjali-wps** [wpswings/upsell-order-bump-offer-for-woocommerce#136]
WP Version - 6.3.2
WC Version - 8.2.1
Plugin Version - 2.2.8
Disclaimer - Please Remove Skype link  
![image](https://github.com/wpswings/upsell-order-bump-offer-for-woocommerce/assets/129398279/a150c21f-560f-460a-8db0-dd98b841dc72)

**Comment by prince-cedcoss** [comment]
Fixed

**Comment by pranjali-wps** [comment]
issue fixed
