### ISSUE TITLE
QA ISSUE

### ISSUE THREAD

**Issue by pranjali-wps** [wpswings/upsell-order-bump-offer-for-woocommerce#138]
WP - 6.3.2
WC - 8.2.1
Description- QA ISSUE

https://docs.google.com/document/d/1PPHD1eteI-xFbrMkIITqEGXg1Mtc714q-X6xg3IC3Ts/edit?usp=sharing

**Comment by prince-cedcoss** [comment]
all issue are fixed

**Comment by pranjali-wps** [comment]
issue fixed
