### ISSUE TITLE
ShortCode is applied and also displayed properly but it is displayed as "Publishing failed".

### ISSUE THREAD

**Issue by pranjali-wps** [wpswings/upsell-order-bump-offer-for-woocommerce#140]
WP Version - 6.4.2
WC Version - 8.5.0
Plugin Version - 2.3.0
Description - ShortCode is applied and also displayed properly but it is displayed as "Publishing failed".

![image](https://github.com/wpswings/upsell-order-bump-offer-for-woocommerce/assets/129398279/ebf28fe0-ee7b-4e2f-9364-bb65d383be6f)

**Comment by prince-cedcoss** [comment]
this is not a issue a it is permalinks setting concern, it get fixed automatically.It will get showed and render without causing any issue.

**Comment by pranjali-wps** [comment]
verified
