### ISSUE TITLE
New template For order Bump 

### ISSUE THREAD

**Issue by pranjali-wps** [wpswings/upsell-order-bump-offer-for-woocommerce#141]
WP Version - 6.4.2
WC Version - 8.5.0
Plugin Version - 2.3.0
Description - The New Template listing should be at the top of the templates list.

![image](https://github.com/wpswings/upsell-order-bump-offer-for-woocommerce/assets/129398279/fb538db7-e4bc-4ee3-9144-265d28c16569)

**Comment by prince-cedcoss** [comment]
fixed now

**Comment by pranjali-wps** [comment]
issue fixed
