### ISSUE TITLE
The new template is not displayed properly.

### ISSUE THREAD

**Issue by pranjali-wps** [wpswings/upsell-order-bump-offer-for-woocommerce#142]
WP Version - 6.4.2
WC Version - 8.5.0
Plugin Version - 2.3.0

Description - The new template is not displayed properly.

**Template**

![image](https://github.com/wpswings/upsell-order-bump-offer-for-woocommerce/assets/129398279/1ccc0c4c-5dd3-4f2f-a8f1-e2aae518b85b)

**Issue**

![image](https://github.com/wpswings/upsell-order-bump-offer-for-woocommerce/assets/129398279/fcf3e850-137b-4430-979a-91cc821cf067)

**Comment by prince-cedcoss** [comment]
fixed now
