### ISSUE TITLE
Shortcode Order Bump issue

### ISSUE THREAD

**Issue by pranjali-wps** [wpswings/upsell-order-bump-offer-for-woocommerce#144]
WP version - 6.4.2
WC version - 8.5.0
Plugin version - ORG
Description - When I click on Shortcode "Shortcode Order Bump" the "Enable permalink on product title and image" Toggle is working.

[scrnli_16_01_2024_11-19-05.webm](https://github.com/wpswings/upsell-order-bump-offer-for-woocommerce/assets/129398279/2758df10-c686-4576-b174-4fcb84d6e877)

**Comment by prince-cedcoss** [comment]
fixed now

**Comment by pranjali-wps** [comment]
issue fixed
