### ISSUE TITLE
 In the ORG plugin, the AB Testing feature toggle is enabled.

### ISSUE THREAD

**Issue by pranjali-wps** [wpswings/upsell-order-bump-offer-for-woocommerce#146]
WP Version - 6.4.3
WC Version - 8.6.1
Description - In the ORG plugin, the AB Testing feature toggle is enabled.

[scrnli_05_03_2024_16-45-19.webm](https://github.com/wpswings/upsell-order-bump-offer-for-woocommerce/assets/129398279/976d7538-bbad-4393-9cdf-eaf6a5e76521)

**Comment by prince-cedcoss** [comment]
fixed now

**Comment by pranjali-wps** [comment]
issue fixed
