### ISSUE TITLE
When I Install the plugin Deprecated and notice is displayed.

### ISSUE THREAD

**Issue by pranjali-wps** [wpswings/upsell-order-bump-offer-for-woocommerce#148]
WP Version - 6.5.2
WC Version - 8.8.2
Plugin Version - 2.3.2
Description - When I Install the plugin Deprecated and notice is displayed.

![image](https://github.com/wpswings/upsell-order-bump-offer-for-woocommerce/assets/129398279/b3f3ee36-ac6f-4eea-9e5a-e5f189d16afa)

**Comment by prince-cedcoss** [comment]
fixed now

**Comment by pranjali-wps** [comment]
issue fixed
