### ISSUE TITLE
 When I click on the overview page then a deprecated is displayed.

### ISSUE THREAD

**Issue by pranjali-wps** [wpswings/upsell-order-bump-offer-for-woocommerce#149]
WP Version - 6.5.2
WC Version - 8.8.2
Plugin Version - 2.3.2
Description - When I click on the overview page then a deprecated is displayed.

![image](https://github.com/wpswings/upsell-order-bump-offer-for-woocommerce/assets/129398279/8ce8e762-0e7d-4ca1-accc-2aca9010960b)

**Comment by prince-cedcoss** [comment]
fixed now

**Comment by pranjali-wps** [comment]
issue fixed
