### ISSUE TITLE
Newly added banner image issue- clear button issue

### ISSUE THREAD

**Issue by pranjali-wps** [wpswings/upsell-order-bump-offer-for-woocommerce#150]
WP Version - 6.5.2
WC Version - 8.8.2
Plugin Version - 2.3.2
Description - The "Clear" button is not displayed properly and also when I click on the clear button, it redirects to the Plugins PRO page. It should close the pop-up after clicking on the Clear button.

![image](https://github.com/wpswings/upsell-order-bump-offer-for-woocommerce/assets/129398279/0919ad06-d3a7-4c46-854b-7810c38c2c3f)

[scrnli_23_04_2024_11-32-11.webm](https://github.com/wpswings/upsell-order-bump-offer-for-woocommerce/assets/129398279/7b98405b-ac8f-45c6-a73f-92b9e243c749)

**Comment by prince-cedcoss** [comment]
fixednow

**Comment by pranjali-wps** [comment]
issue fixed
