### ISSUE TITLE
 There should be added a UTM for the redirection of the popup.

### ISSUE THREAD

**Issue by pranjali-wps** [wpswings/upsell-order-bump-offer-for-woocommerce#151]
WP Version - 6.5.2
WC Version - 8.8.2
Plugin Version - 2.3.2
Description - There should be added a UTM for the redirection of the popup. It is redirected to the Order Bump PRO plugin.

[scrnli_23_04_2024_12-06-37.webm](https://github.com/wpswings/upsell-order-bump-offer-for-woocommerce/assets/129398279/a938ebf8-4bf0-4ec2-bc05-e21480cb2fee)

**Comment by prince-cedcoss** [comment]
fixed now

**Comment by pranjali-wps** [comment]
issue fixed
