### ISSUE TITLE
 Spelling issue 

### ISSUE THREAD

**Issue by pranjali-wps** [wpswings/upsell-order-bump-offer-for-woocommerce#152]
WP Version - 6.5.2
WC Version - 8.8.2
Plugin Version - 2.3.2
Description - Spelling issue 

![image](https://github.com/wpswings/upsell-order-bump-offer-for-woocommerce/assets/129398279/3d2160b1-2cc5-41e5-b6ba-72b968b1ddde)

**Before Add to Cart**

![image](https://github.com/wpswings/upsell-order-bump-offer-for-woocommerce/assets/129398279/5dc55b2e-8801-4d37-905d-66033a85f07f)

**discount--> Discount**

![image](https://github.com/wpswings/upsell-order-bump-offer-for-woocommerce/assets/129398279/132dd89c-5381-4cf1-a998-25b905bdeaef)

**Comment by prince-cedcoss** [comment]
fixed now

**Comment by pranjali-wps** [comment]
issue fixed
