### ISSUE TITLE
The "+Create New Order Bump" button is not working.

### ISSUE THREAD

**Issue by pranjali-wps** [wpswings/upsell-order-bump-offer-for-woocommerce#153]
WP Version - 6.5.2
WC Version - 8.8.2
Plugin Version - 2.3.2
Description - The "+Create New Order Bump" button is not working.

![image](https://github.com/wpswings/upsell-order-bump-offer-for-woocommerce/assets/129398279/ad9f1304-2f19-4610-a919-2026d0ce244d)

[scrnli_23_04_2024_12-13-56.webm](https://github.com/wpswings/upsell-order-bump-offer-for-woocommerce/assets/129398279/8f9b4f6d-e43c-4770-8d04-2451e012d207)

**Comment by prince-cedcoss** [comment]
fixed now

**Comment by pranjali-wps** [comment]
still pending issue

**Comment by prince-cedcoss** [comment]
fixed

**Comment by pranjali-wps** [comment]
issue fixed
