### ISSUE TITLE
Order bump is displayed twicely on checkout page.

### ISSUE THREAD

**Issue by pranjali-wps** [wpswings/upsell-order-bump-offer-for-woocommerce#154]
WP Version - 6.5.2
WC Version - 8.8.2
Plugin Version - 2.3.2
Theme issue - WThe WordPress default theme,twice2023, 2022
Description - Order bump is displayed twice on the checkout page.

![image](https://github.com/wpswings/upsell-order-bump-offer-for-woocommerce/assets/129398279/cb0ac363-44f4-4159-9a8a-d36b9f132c7c)

**Comment by prince-cedcoss** [comment]
the themes 24, and 23 are not that stable so, there may be chances that the js will not work.
so, this is a theme-dependent issue.They are very rare use themes.
But the functionality is worked in a standard theme.
and fixed

**Comment by prince-cedcoss** [comment]
fixed now

**Comment by pranjali-wps** [comment]
issue fixed
