### ISSUE TITLE
The order bump is working also twice

### ISSUE THREAD

**Issue by pranjali-wps** [wpswings/upsell-order-bump-offer-for-woocommerce#155]
WP Version - 6.5.2
WC Version - 8.8.2
Plugin Version - 2.3.2
Theme issue - WordPress default theme , 2024, 2023, 2022
Description - The order bump is working also twice. If I click on both checkboxes then both act like order bump products.

https://github.com/wpswings/upsell-order-bump-offer-for-woocommerce/assets/129398279/220ff4f5-c0d6-4e2b-bd23-61f9c12114ff

**Comment by pranjali-wps** [comment]
still pending

**Comment by prince-cedcoss** [comment]
fixed now

**Comment by pranjali-wps** [comment]
issue fixed
