### ISSUE TITLE
I activate the ORG plugin then the Service icon is conflicted.

### ISSUE THREAD

**Issue by pranjali-wps** [wpswings/upsell-order-bump-offer-for-woocommerce#156]
WP Version - 6.5.2
WC Version - 8.8.3
Plugin Version - 2.3.2
Description - 1) If I activate the ORG plugin then the Service icon is conflicted.

2) Issue is also present in PRO plugin, If I activate the ORG plugin then the Service icon is conflicted.

![image](https://github.com/wpswings/upsell-order-bump-offer-for-woocommerce/assets/129398279/670875b0-d9d5-4e37-a1dc-1e833586d518)
 

![image](https://github.com/wpswings/upsell-order-bump-offer-for-woocommerce/assets/129398279/2641aeec-f9a5-49c8-9ae2-aafb1cacb87a)

**Comment by prince-cedcoss** [comment]
fixed now

**Comment by pranjali-wps** [comment]
issue fixed
