### ISSUE TITLE
Please add the Required woocommerce code on org and pro both.

### ISSUE THREAD

**Issue by pranjali-wps** [wpswings/upsell-order-bump-offer-for-woocommerce#158]
WP Version - 6.5.4
WC Version - 8.9.3
Plugin_Version -  pro
Description - Please add the Required woocommerce code on org and pro both.

![image](https://github.com/wpswings/upsell-order-bump-offer-for-woocommerce/assets/129398279/1b4a423e-7cfc-40e1-a8fc-64af3bd2b21b)

**Comment by prince-cedcoss** [comment]
fixes

**Comment by pranjali-wps** [comment]
issue fixed
