### ISSUE TITLE
 After enable the pro plugin it displays a warning.

### ISSUE THREAD

**Issue by pranjali-wps** [wpswings/upsell-order-bump-offer-for-woocommerce#161]
WP version - 6.6.2
WC Version - 9.3.2
Plugin version - 1.3.1
Description - After enable the pro plugin it displays a warning.

![image](https://github.com/user-attachments/assets/4b3afffb-89b7-42b4-9e25-527e64f36a68)

**Comment by prince-cedcoss** [comment]
the issue is fixed now.

**Comment by pranjali-wps** [comment]
issue fixed
