### ISSUE TITLE
Themes are not compatible with our ORG and PRO plugins by default

### ISSUE THREAD

**Issue by pranjali-wps** [wpswings/upsell-order-bump-offer-for-woocommerce#162]
WP Version- 6.7.1
WC Version- 9.4.2
Plugin Version- 2.4.3
Themes - 2025,2024,2023 
Disclaimer: Themes are not compatible with our ORG and PRO plugins by default. The order bump offer is displayed twice.

![image](https://github.com/user-attachments/assets/9d9e6ef2-12be-4440-a6fb-60eb31ee9b21)

**Comment by prince-cedcoss** [comment]
fixed the issue now

**Comment by pranjali-wps** [comment]
issue fixed
