### ISSUE TITLE
There should be a pro plugin popup if an admin clicks on "+Create New Order Bump"

### ISSUE THREAD

**Issue by pranjali-wps** [wpswings/upsell-order-bump-offer-for-woocommerce#163]
WP Version- 6.7.1
WC Version- 9.4.2
Plugin Version- 2.4.3
Disclaimer - There should be a pro plugin popup if an admin clicks on "+Create New Order Bump".

![image](https://github.com/user-attachments/assets/1f9c47af-781b-405d-ac27-7ce10c04a833)

**Comment by prince-cedcoss** [comment]
added now

**Comment by pranjali-wps** [comment]
issue fixed
