### ISSUE TITLE
issue with the offer image

### ISSUE THREAD

**Issue by prateek-cedcoss** [wpswings/upsell-order-bump-offer-for-woocommerce#85]
os: window11
wp: 5.8.2
wc: 6.0.0
version: 2.0.2
path: save order bump
description: after photo get upload in offer image, if we click on the beside on the blank space then also photo upload option appear. 

![image](https://user-images.githubusercontent.com/86113814/148165724-d3b01ca7-c216-4540-9cc4-2e560f7dd378.png)

**Comment by ahmadabbas-cedcoss** [comment]
enhancement will be dealt in next update dont close it for now

**Comment by Sukirti-CEDCOSS** [comment]
verified
