### ISSUE TITLE
issue with the submission form

### ISSUE THREAD

**Issue by prateek-cedcoss** [wpswings/upsell-order-bump-offer-for-woocommerce#86]
os: window11
wp: 5.8.2
wc: 6.0.0
version: 2.0.2
description: issue with the form submission of org and pro, as no data received.

**Comment by ahmadabbas-cedcoss** [comment]
issue solved

**Comment by prateek-cedcoss** [comment]
not solve
getting double value in deactivate from
![image](https://user-images.githubusercontent.com/86113814/148555494-36dd56bd-cb81-4050-9412-417c9be0933b.png)

**Comment by ahmadabbas-cedcoss** [comment]
issue solved in the previous update

**Comment by AnuraktSachan-CEDCOSS** [comment]
okay
