### ISSUE TITLE
getting php notice while placing an order

### ISSUE THREAD

**Issue by prateek-cedcoss** [wpswings/upsell-order-bump-offer-for-woocommerce#87]
os: window11
wp: 5.8.3
wc: 6.0.0
path: thank you 
description: when we select order bump and place an order then this php notice appear.
![image](https://user-images.githubusercontent.com/86113814/148537759-fee83b8a-c750-43b3-8e8a-4921de2f5e31.png)

**Comment by ahmadabbas-cedcoss** [comment]
issue solved

**Comment by AnuraktSachan-CEDCOSS** [comment]
okay
