### ISSUE TITLE
issue with license

### ISSUE THREAD

**Issue by kavya-cedcoss** [wpswings/upsell-order-bump-offer-for-woocommerce#88]
when no. of trial days are over, in that case the org features also gets disabled
![screenshot-nimbus-capture-2022 02 20-14_57_36 (1)](https://user-images.githubusercontent.com/63343498/150502581-0b8afe5f-9a81-40dd-92fa-20854e201edd.png)

**Comment by AnuraktSachan-CEDCOSS** [comment]
![image](https://user-images.githubusercontent.com/76723393/160582169-3eeb25fd-d61e-4232-a73e-93f326c5346f.png)

**Comment by ahmadabbas-cedcoss** [comment]
old issue please close

**Comment by AnuraktSachan-CEDCOSS** [comment]
But this issue is still here, when 30 days are compleated then pro will disfunctional but org are working well.

**Comment by ahmadabbas-cedcoss** [comment]
appropriate notice is printend please check on the above scrshot it is not an issue

**Comment by AnuraktSachan-CEDCOSS** [comment]
okay
