### ISSUE TITLE
Notice on order bump offer.

### ISSUE THREAD

**Issue by AnuraktSachan-CEDCOSS** [wpswings/upsell-order-bump-offer-for-woocommerce#91]
**Bug Name -** Notice on order bump offer.
**Area Path -** 
**Status -** New
**Woo Commerce Version -** 6.2.1
**WordPress Version -** 5.9
**Plugin Version -** 2.0.3
**Description -**

![image](https://user-images.githubusercontent.com/76723393/156739559-18b686d5-d79c-48ff-90ae-682c4567cb40.png)

![image](https://user-images.githubusercontent.com/76723393/156868363-a8cbe12a-2ecb-4103-89fc-6c77b9005cc9.png)

**Comment by ahmadabbas-cedcoss** [comment]
issue solved

**Comment by AnuraktSachan-CEDCOSS** [comment]
okay
