### ISSUE TITLE
"Upload Image" setting is not working.

### ISSUE THREAD

**Issue by AnuraktSachan-CEDCOSS** [wpswings/upsell-order-bump-offer-for-woocommerce#92]
**Bug Name -** "Upload Image" setting is not working.
**Area Path -** 
**Status -** New
**Woo Commerce Version -** 6.2.1
**WordPress Version -** 5.9
**Plugin Version -** 2.0.3
**Description -**

![image](https://user-images.githubusercontent.com/76723393/156742530-1ac2b98b-52d6-4b49-a6f0-20e53655fa0e.png)

**Comment by ahmadabbas-cedcoss** [comment]
issue solved

**Comment by AnuraktSachan-CEDCOSS** [comment]
okay
