### ISSUE TITLE
Offer Product is working like save setting button.

### ISSUE THREAD

**Issue by AnuraktSachan-CEDCOSS** [wpswings/upsell-order-bump-offer-for-woocommerce#94]
**Bug Name -** Offer Product is working like save setting button.
**Area Path -** 
**Status -** New
**Woo Commerce Version -** 6.4.1
**WordPress Version -** 5.9.3
**Plugin Version -** 2.1.2
**Description -**

When you select offer product, order bump are saved automatically.

![image](https://user-images.githubusercontent.com/76723393/164751319-85cd95d2-4a10-4438-8ca2-b986cd5ec869.png)

**Comment by ahmadabbas-cedcoss** [comment]
this is the functionality of the plugin not an issue

**Comment by AnuraktSachan-CEDCOSS** [comment]
okay.
