### ISSUE TITLE
Issue in spacing bar. 

### ISSUE THREAD

**Issue by AnuraktSachan-CEDCOSS** [wpswings/upsell-order-bump-offer-for-woocommerce#95]
**Bug Name -** Issue in spacing bar. 
**Area Path -** 
**Status -** New
**Woo Commerce Version -** 6.4.1
**WordPress Version -** 5.9.3
**Plugin Version -** 2.1.2
**Description -**

First of all you keep the spacing bar  on minimum length and save the setting then you see spacing bar move on mid.

![image](https://user-images.githubusercontent.com/76723393/164765101-33c4bb5c-8b95-4307-bc7c-8498ca82021d.png)

**Comment by ahmadabbas-cedcoss** [comment]
issue solved now minimum value is 10

**Comment by AnuraktSachan-CEDCOSS** [comment]
okay
