### ISSUE TITLE
Multiple Order Bumps Count

### ISSUE THREAD

**Issue by AnuraktSachan-CEDCOSS** [wpswings/upsell-order-bump-offer-for-woocommerce#96]
**Bug Name -** Multiple Order Bumps Count
**Area Path -** 
**Status -** New
**Woo Commerce Version -** 6.4.1
**WordPress Version -** 5.9.3
**Plugin Version -** 2.1.2
**Description -**

When I am not able to create multiple bumps so I use this feature?

![image](https://user-images.githubusercontent.com/76723393/164888921-27db783b-3342-4890-b8d2-7d37078aae84.png)

**Comment by ahmadabbas-cedcoss** [comment]
this is a previous functionality and will remain as it is

**Comment by AnuraktSachan-CEDCOSS** [comment]
okay but we will change it.

**Comment by Sukirti-CEDCOSS** [comment]
verified
