### ISSUE TITLE
Malware Issues

### ISSUE THREAD

**Issue by AnuraktSachan-CEDCOSS** [wpswings/upsell-order-bump-offer-for-woocommerce#98]
**Bug Name -** Malware Issues
**Area Path -** 
**Status -** New
**Woo Commerce Version -** 6.5.1
**WordPress Version -** 6.0.0
**Plugin Version -** 2.1.3
**Description -**

DodgyPhp /home/cedcoss/Desktop/upsell-order-bump-offer-for-woocommerce/reporting/class-wps-upsell-order-bump-report-sales-by-product.php
0x4e5:$execution2: array_filter( array_map( 'absint', $_GET
ObfuscatedPhp /home/cedcoss/Desktop/upsell-order-bump-offer-for-woocommerce/includes/class-upsell-order-bump-offer-for-woocommerce-global-functions.php
0x7c81:$concat_with_spaces: $bumphtml .= '<a target="' . $wps_bump_target_attr . '" href="' . $bump_offer_product_permalink . '"><img class="wps_upsell_offer_img" src="' . $image . '" data-id="' . $bump['id'] . 
0x7d5d:$concat_with_spaces: $bumphtml .= '<div class="wps_upsell_offer_product_content"> <h4 class="wps_bump_name" data-qty_allowed="' . $wps_upsell_enable_quantity . '" data-wps_is_fixed_qty="' . $wps_is_fixed_qty . '" data-wps_qty="' . $wps_upsell_bump_products_fixed_quantity . '"><a target="' . $wps_bump_target_attr . '" class="wps_upsell_product_permalink" href="' . $bump_offer_product_permalink . '">' . $bump['name'] . 
0x7dca:$concat_with_spaces: $wps_upsell_enable_quantity . '" data-wps_is_fixed_qty="' . $wps_is_fixed_qty . '" data-wps_qty="' . $wps_upsell_bump_products_fixed_quantity . '"><a target="' . $wps_bump_target_attr . '" class="wps_upsell_product_permalink" href="' . $bump_offer_product_permalink . '">' . $bump['name'] . 
0x7e06:$concat_with_spaces: $wps_is_fixed_qty . '" data-wps_qty="' . $wps_upsell_bump_products_fixed_quantity . '"><a target="' . $wps_bump_target_attr . '" class="wps_upsell_product_permalink" href="' . $bump_offer_product_permalink . '">' . $bump['name'] . 
0x8365:$concat_with_spaces: $bumphtml .= '<div class="wps_upsell_offer_product_content"> <h4 class="wps_bump_name" data-qty_allowed="' . $wps_upsell_enable_quantity . '" data-wps_is_fixed_qty="' . $wps_is_fixed_qty . '" data-wps_qty="' . $wps_upsell_bump_products_fixed_quantity . '">' . $bump['name'] .

**Comment by AnuraktSachan-CEDCOSS** [comment]
DodgyPhp /home/cedcoss/Desktop/upsell-order-bump-offer-for-woocommerce/reporting/class-wps-upsell-order-bump-report-sales-by-product.php
0x4e5:$execution2: array_filter( array_map( 'absint', $_GET
ObfuscatedPhp /home/cedcoss/Desktop/upsell-order-bump-offer-for-woocommerce/includes/class-upsell-order-bump-offer-for-woocommerce-global-functions.php
0x801f:$concat_with_spaces: $bumphtml .= '<div class="wps_upsell_offer_product_content"> <h4 class="wps_bump_name" data-qty_allowed="' . $wps_upsell_enable_quantity . '" data-wps_is_fixed_qty="' . $wps_is_fixed_qty . '" data-wps_qty="' . $wps_upsell_bump_products_fixed_quantity . '"><a target="' . $wps_bump_target_attr . '" class="wps_upsell_product_permalink" href="' . $bump_offer_product_permalink . '">' . $bump['name'] . 
0x808c:$concat_with_spaces: $wps_upsell_enable_quantity . '" data-wps_is_fixed_qty="' . $wps_is_fixed_qty . '" data-wps_qty="' . $wps_upsell_bump_products_fixed_quantity . '"><a target="' . $wps_bump_target_attr . '" class="wps_upsell_product_permalink" href="' . $bump_offer_product_permalink . '">' . $bump['name'] . 
0x80c8:$concat_with_spaces: $wps_is_fixed_qty . '" data-wps_qty="' . $wps_upsell_bump_products_fixed_quantity . '"><a target="' . $wps_bump_target_attr . '" class="wps_upsell_product_permalink" href="' . $bump_offer_product_permalink . '">' . $bump['name'] . 
0x8632:$concat_with_spaces: $bumphtml .= '<div class="wps_upsell_offer_product_content"> <h4 class="wps_bump_name" data-qty_allowed="' . $wps_upsell_enable_quantity . '" data-wps_is_fixed_qty="' . $wps_is_fixed_qty . '" data-wps_qty="' . $wps_upsell_bump_products_fixed_quantity . '">' . $bump['name'] .

**Comment by prince-cedcoss** [comment]
fixed

**Comment by AnuraktSachan-CEDCOSS** [comment]
ok
